// <auto-generated />
namespace gallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class try0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(try0));
        
        string IMigrationMetadata.Id
        {
            get { return "202102250338362_try0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
